### ISSUE TITLE
Could nfs-client provisioner make PV directory if it's not already there?

### ISSUE THREAD

**Issue by hdave** [kubernetes-incubator/external-storage#1032]
Our project is successfully using nfs-client provisioner to create dynamic volumes on behalf of a claim.  However, for static (e.g. manually created) volumes, the nfs path has to exist in order for the PV to function.  This is a little inconvenient.  Ideally, we could apply a resource as follows where `/mnt/data/kubernetes` is our export:

```
kind: PersistentVolume
metadata:
  name: my-pv-test
spec:
  accessModes:
  - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: my-claim
    namespace: default
  nfs:
    path: /mnt/data/kubernetes/my-pv-test
    server: 192.168.1.10
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-retain
```

and the directory `my-pv-test` would be made for me.
