### ISSUE TITLE
How to configure ClusterRole

### ISSUE THREAD

**Issue by fangchao117** [kubernetes-incubator/external-storage#1061]
My sc namespace is cephfs

kubectl get sc
NAME     PROVISIONER       AGE
cephfs   ceph.com/cephfs   17s

Created pvc using monitoring namespace

cephfs-provisioner error logs：
![462dd1e3-109c-4360-9547-93eb7525309a](https://user-images.githubusercontent.com/20237080/48545928-f8033900-e901-11e8-9adb-35b177b4b43d.png)

clusterrole.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cephfs-provisioner
  namespace: cephfs
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["policy"]
    resourceNames: ["cephfs-provisioner"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]

pvc.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: monitoring
  name: cephfs-pv-grafana
  annotations:
    volume.beta.kubernetes.io/storage-class: "cephfs"
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

**Comment by MartinForReal** [comment]
please delete secret resource cephfs-pv-grafana-secret under monitoring namespace.

**Comment by fangchao117** [comment]
> 
> 
> please delete secret resource cephfs-pv-grafana-secret under monitoring namespace.

Thank you, but you need to delete each time you create a PVC. And cephfs error input/output error occurs when accessing the service log when mounting to other services

**Comment by whereisaaron** [comment]
@fangchao117 the cephfs provisioner, by default, expects to read the admin secret from 'kube-system' and create PVC secrets in the same namespace as each PVC. But the sample RBAC doesn't actually include those permissions (@wongma7 should it?). You can either set `--secret-namespace="cephfs"` and keep all the Secrets in the one namespace, or you can extend the ClusterRole to allow Secret creation elsewhere.

So you could add this to you ClusterRole, if you'd like to use the default approach ('list' verb might not be needed, haven't confirmed that).
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: cephfs-provisioner
namespace: cephfs
rules:
  ...
  # Default is to create secrets the same namespace as PVC
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create","delete"]
```
