### ISSUE TITLE
Unable to mount efs

### ISSUE THREAD

**Issue by sujithvs74** [kubernetes-incubator/external-storage#1065]
I am getting below error while deploying efs-provisioner, can somebody guide me on this.

Do I need to install nfs-util package in pod level to make it work.

I am using mount target IP to mount EFS to efs-provisioner.

Volume Mount :
```
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: 10.10.10.87
            path: /
```

Configmap

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
data:
  file.system.id: fs-fc78a934
  aws.region: us-west-2
  provisioner.name: dev.efs.example.com/aws-efs
---
```

```
Events:
  Type     Reason       Age   From                                                Message
  ----     ------       ----  ----                                                -------
  Normal   Scheduled    3m    default-scheduler                                   Successfully assigned default/efs-provisioner-664d9ffcf-9pgqj to ip-10-10-10-31.us-west-2.compute.internal
  Warning  FailedMount  3m    kubelet, ip-10-10-10-31.us-west-2.compute.internal  MountVolume.SetUp failed for volume "pv-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/258638b4-ec80-11e8-b0df-024ebf7005c2/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs 10.10.10.87:/ /var/lib/kubelet/pods/258638b4-ec80-11e8-b0df-024ebf7005c2/volumes/kubernetes.io~nfs/pv-volume
Output: Running scope as unit run-35218.scope.
mount: wrong fs type, bad option, bad superblock on 10.10.10.87:/,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
  Warning  FailedMount  3m  kubelet, ip-10-10-10-31.us-west-2.compute.internal  MountVolume.SetUp failed for volume "pv-volume" : mount failed: exit status 32

```
