### ISSUE TITLE
EFS Provisioner in each namespace?

### ISSUE THREAD

**Issue by vishal24tuniki** [kubernetes-incubator/external-storage#1097]
Hi,

Do we need to create the combination of resources
configmap, efs-provisioner deployment in each namespace where we create PersistentVolumeClaim which in-turn is mounted on my application pod?

I just tested out with configmap, serviceaccount, efs-provisioner in "default" namespace & my PVC in another namespace (say "example" namespace) & run a pod in example namepace mounting the PVC created in example namespace. It worked fine. Just wanted to confirm if it's right

**Comment by jhlav** [comment]
No, you don't have to create these in each namespace.  You can use just one group of resources for your whole Kubernetes cluster.  The storage class created for efs-provisioner is not limited to any namespace, so Pods will be able to use that storage class by simply referencing it like so:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-app-pv-claim
  namespace: example-app
  labels:
    app: example-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: "aws-efs"
  selector:
    matchLabels:
      app: example-app
```

I hope that helps!

/close
