### ISSUE TITLE
[aws efs] ProvisioningFailed - no volume plugin matched

### ISSUE THREAD

**Issue by harik8** [kubernetes-incubator/external-storage#1111]
I followed the deployment steps and deployed efs-provisioner on kubernetes. But I am getting below error, 

```
$ kubectl describe pvc efs -n dev
Name:		efs
Namespace:	dev
StorageClass:	aws-efs
Status:		Pending
Volume:		
Labels:		<none>
Annotations:	volume.beta.kubernetes.io/storage-class=aws-efs
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  8m		23s		11	persistentvolume-controller			Warning		ProvisioningFailed	no volume plugin matched
```

**Comment by Art3mK** [comment]
I'm having the same issue on EKS, and don't know how to debug it. There are no any erros in efs-provisioner pod logs, EFS is mounted by efs-provisioner, but pvcs are pending with that `no volume plugin matched` message.

**Comment by Art3mK** [comment]
Looks like it's smth with latest versions. Works fine with chart version `0.1.3` (which uses `0.1.2` image) In order to provision PVC with `0.2.0` chart and `v2.1.0-k8s1.11` image you'll need to add `volume.beta.kubernetes.io/storage-provisioner: %your provisionerName%` annotation to your PVC.

provisioner name could be checked in storage class:
```
➜  ~ kubectl get storageclasses.storage.k8s.io efs -o yaml --export                                                     
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: null
  labels:
    app: efs-provisioner
    chart: efs-provisioner-0.1.3
    env: dev
    heritage: Tiller
    release: efs-provisioner
  name: efs
  selfLink: /apis/storage.k8s.io/v1/storageclasses/efs
parameters:
  gidAllocate: "true"
  gidMax: "50000"
  gidMin: "40000"
provisioner: kubernetes.io/aws-efs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
