### ISSUE TITLE
nfs-provisioner - pod fails with mkdir file exists error

### ISSUE THREAD

**Issue by matthen** [kubernetes-incubator/external-storage#1128]
Hi and thanks in advance for any help!

I am using an `nfs-client-provisioner` deployment, yaml copied below. When starting pods, I get this error on some nodes:

```
Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      error while creating mount source path '/var/lib/kubelet/pods/f376aa1c-29bd-11e9-b82a-b827eb21c804/volumes/kubernetes.io~nfs/pvc-906dd368-22ec-11e9-b375-b827eb21c804': mkdir /var/lib/kubelet/pods/f376aa1c-29bd-11e9-b82a-b827eb21c804/volumes/kubernetes.io~nfs/pvc-906dd368-22ec-11e9-b375-b827eb21c804: file exists
      Exit Code:    128
      Started:      Thu, 07 Feb 2019 13:11:44 +0800
      Finished:     Thu, 07 Feb 2019 13:11:44 +0800
```

Any ideas what might be wrong?

If I ssh to the node, I find that the `pvc-906dd368` is a 'stale file handle'

deployment yaml:
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
        version: v0
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner-arm:v3.1.0-k8s1.11
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-storage
            - name: NFS_SERVER
              value: 192.168.1.44
            - name: NFS_PATH
              value: /opt/nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.1.44
            path: /opt/nfs
```
