### ISSUE TITLE
nfs-client provisioner pod keep in ContainerCreating state

### ISSUE THREAD

**Issue by tylyccn** [kubernetes-incubator/external-storage#1160]
Hi,

I need created a NFS client storage class in k8s network for Jenkins X usage.
My k8s has one master and one work node, the version is 1.11
helm version is (both client and server): v2.13.1

The command I created the nfs-client is (I also tried mount version 4, result is the same):

helm install --name my-release stable/nfs-client-provisioner --set nfs.server=10.182.12.149 --set nfs.path=/home/ocsg/nfs/jenkinsx  --set storageClass.defaultClass=true --set nfs.mountOptions="{tcp,nfsvers=3}"

Helm doesn't report any error, and sc can be seen in k8s:

[root@bej312336 storageClass]# kubectl describe sc
Name:                  nfs-client
IsDefaultClass:        Yes
Annotations:           storageclass.kubernetes.io/is-default-class=true
Provisioner:           cluster.local/my-release-nfs-client-provisioner
Parameters:            archiveOnDelete=true
AllowVolumeExpansion:  True
MountOptions:
  tcp
  nfsvers=4
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>

But seen from the pod:

[root@bej312336 storageClass]# kubectl get pod
NAME                                                 READY     STATUS              RESTARTS   AGE
my-release-nfs-client-provisioner-5b98cd6d97-stpqd   0/1       ContainerCreating   0          14s

I also tried to mount the NFS locally in linux command and it also works for both V3 and V4.

Could anyone provide any instructions for the troubleshooting?

**Comment by PigeonCai** [comment]
have the same error

**Comment by rubiktubik** [comment]
Hi, i had the same error.

I solved this problem with also set the right path:
```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: <YOUR NFS SERVER HOSTNAME>
            - name: NFS_PATH
              value: <MY NFS SERVER PATH>
      volumes:
        - name: nfs-client-root
          nfs:
            server: <YOUR NFS SERVER HOSTNAME>
            path: <MY NFS SERVER PATH>
```
i hope it helps someone :-)
