### ISSUE TITLE
[nfs-client-provisioner] ignores a PVC if it has a volumeName in the spec

### ISSUE THREAD

**Issue by sirtux** [kubernetes-incubator/external-storage#1174]
Hi,

I found out that the nfs-client-provisioner is silently ignoring a PersistantVolumeClaim,
if it has a volumeName in the spec,

e.g this is beeing ignored:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-volume-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  volumeName: config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
```

while

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-volume-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
```

is working. 

I would have expected that it works with the volumeName, 
or at least throws an error. 

The logs on the client provisioner pod were completely silent with the PVC with the volumeName...

Thanks,
Tom
