### ISSUE TITLE
[targetd] No Route to Host

### ISSUE THREAD

**Issue by Queuecumber** [kubernetes-incubator/external-storage#1191]
My targetd server is running as a pod in my cluster and exposed via service, the provisioner gets the following error

```
time="2019-07-10T22:17:44Z" level=debug msg="opening connection to targetd:  http://admin:none@targetd:0/targetrpc" 
time="2019-07-10T22:17:44Z" level=debug msg="targetd client created" 
time="2019-07-10T22:17:47Z" level=warning msg="{\"code\":-32603,\"message\":\"Post http://admin:none@targetd:0/targetrpc: dial tcp 10.245.138.191:0: getsockopt: no route to host\"}" 
time="2019-07-10T22:17:47Z" level=warning msg="{\"code\":-32603,\"message\":\"Post http://admin:none@targetd:0/targetrpc: dial tcp 10.245.138.191:0: getsockopt: no route to host\"}" 
ERROR: logging before flag.Parse: E0710 22:17:47.186752       1 controller.go:808] Failed to provision volume for claim "storage/myclaim" with StorageClass "block": 
```

if I shell into the pod I can curl that IP address no problem, any idea why whatever the go library is would refuse to connect?

**Comment by Queuecumber** [comment]
It's because the port isnt being set properly, I originally assumed that ":0" was some artifact of the print command not being right, it turns out that for whatever reason your default value of 18700 is not being used its defaulting to 0. Setting `TARGETD_PORT` environment variable does work though. This should probably be put in the readme. Or fixed whichever.

**Comment by w1ndy** [comment]
Setting only ``TARGETD_ADDRESS`` works for me... Could you provide your detailed pod and storage class configurations so I may come up with a potential fix? Also you can try the latest image instead, as described in https://github.com/kubernetes-incubator/external-storage/issues/1152#issuecomment-508976553.

**Comment by Queuecumber** [comment]
I really didnt change anything of consequence beyond the defaults in the repository, here it is with redacted names

```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: iscsi-provisioner
  namespace: storage
  labels:
    app: iscsi-provisioner
spec:
  selector:
    matchLabels:
      app: iscsi-provisioner
  template:
    metadata:
      labels:
        app: iscsi-provisioner
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: storage
                    operator: Exists
      containers:
        - name: iscsi-provisioner
          imagePullPolicy: Always
          image: quay.io/external_storage/iscsi-controller:latest
          args:
            - "start"
          env:
            - name: PROVISIONER_NAME
              value: iscsi
            - name: LOG_LEVEL
              value: debug
            - name: TARGETD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: targetd-account
                  key: username
            - name: TARGETD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: targetd-account
                  key: password
            - name: TARGETD_ADDRESS
              value: targetd
            - name: TARGETD_PORT
              value: "18700"
      serviceAccount: iscsi-provisioner
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: block
provisioner: softmax.app/iscsi
parameters:
  targetPortal: <redacted>
  iqn: <redacted>
  volumeGroup: vg-array/array-data
  initiators: <redacted>
```

Beyond the storage class the only thing I changed is to add the correct port number, without which it tries to use port 0. I didn't see any relevant changes when I looked through the commit history between the last image deployment and the updated image from #1152 and I would prefer to use an official image instead of some random persons image. @wongma7 uploading a new image should take all of 5 mins

**Comment by w1ndy** [comment]
That's understandable. However I can't reproduce the error with your configuration, the controller seems to have obtained the correct URL without TARGETD_PORT explicitly set:
```
time="2019-07-16T05:31:17Z" level=debug msg="start called" 
time="2019-07-16T05:31:17Z" level=debug msg="creating in cluster default kube client config" 
time="2019-07-16T05:31:17Z" level=debug msg="kube client config created" config-host="https://10.96.0.1:443" 
time="2019-07-16T05:31:17Z" level=debug msg="creating kube client set" 
time="2019-07-16T05:31:17Z" level=debug msg="kube client set created" 
time="2019-07-16T05:31:17Z" level=debug msg="targed URL http://test:blah@targetd:18700/targetrpc" 
time="2019-07-16T05:31:17Z" level=debug msg="iscsi provisioner created" 
time="2019-07-16T05:31:17Z" level=debug msg="iscsi controller created, running forever..."
```

Could you apply the following deployment and see if the provisioner reports the correct URL in the log?
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: iscsi-provisioner
  labels:
    app: iscsi-provisioner
spec:
  selector:
    matchLabels:
      app: iscsi-provisioner
  template:
    metadata:
      labels:
        app: iscsi-provisioner
    spec:
      containers:
        - name: iscsi-provisioner
          imagePullPolicy: Always
          image: quay.io/external_storage/iscsi-controller:latest
          args:
            - "start"
          env:
            - name: PROVISIONER_NAME
              value: iscsi
            - name: LOG_LEVEL
              value: debug
            - name: TARGETD_USERNAME
              value: test
            - name: TARGETD_PASSWORD
              value: blah
            - name: TARGETD_ADDRESS
              value: targetd
```
