### ISSUE TITLE
efs-provisioner: error retrieving resource lock - endpoint is forbidden

### ISSUE THREAD

**Issue by richstokes** [kubernetes-incubator/external-storage#1209]
Using AWS EFS.

Followed instructions (https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs), applied RBAC yaml. But getting this in the efs-provisioner logs:

```
E0816 19:25:11.059420       1 leaderelection.go:252] error retrieving resource lock default/company.io-efs: endpoints "company.io-efs" is forbidden: User "system:serviceaccount:default:default" cannot get resource "endpoints" in API group "" in the namespace "default"
```

What am I/the docs missing here?

**Comment by richstokes** [comment]
Got it working by changing the RBAC to:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-efs-provisioner
subjects:
  - kind: ServiceAccount
    name: efs-provisioner
     # replace with namespace where provisioner is deployed
    namespace: default
roleRef:
  kind: ClusterRole
  name: efs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
# ---
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: leader-locking-efs-provisioner
# rules:
#   - apiGroups: [""]
#     resources: ["endpoints"]
#     verbs: ["get", "list", "watch", "create", "update", "patch"]
# ---
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: leader-locking-efs-provisioner
# subjects:
#   - kind: ServiceAccount
#     name: efs-provisioner
#     # replace with namespace where provisioner is deployed
#     namespace: default
# roleRef:
#   kind: Role
#   name: leader-locking-efs-provisioner
#   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-provisioner
```

And adding the service account to the manifest.yaml

```
   spec:
      serviceAccount: efs-provisioner
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
```


^^ Found this in an old ticket, but doesn't look like a fix was ever rolled out. Would be worth doing as its quite annoying following docs and example yamls that are out of date and wrong.
