### ISSUE TITLE
NFS-Client creates PV directories with no permission

### ISSUE THREAD

**Issue by Nithinbs18** [kubernetes-incubator/external-storage#1286]
Dear team,
Greetings!!

I have created a windows share,  and I can mount it into any node of my cluster workers and I can write data. So there is no connectivity issue. I want to use this share as a NFS storage for which I have assigned all possible read+write access, included it to Everyone. I tested this out by creating a PV and a PVC the creation and binding are successfully done, but every time I use this storage class for other application the dynamically created PV when mounted to the container inside the pod it is missing the permission it has no permissions (d---------). I created the nfs-client using the stable chart with the below configuration.

```
---
replicaCount: 1
strategyType: Recreate

image:
  repository: quay.io/external_storage/nfs-client-provisioner
  tag: latest
  pullPolicy: IfNotPresent

nfs:
  server: **.**.**.**
  path: /persistent-volume
  mountOptions:
storageClass:
  create: true
  defaultClass: false
  name: nfs-client
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  archiveOnDelete: true
rbac:
  create: true

podSecurityPolicy:
  enabled: false
serviceAccount:
  create: true

  name:

resources: {}
nodeSelector: {}

tolerations: []

affinity: {}
```
Please let me know if there is something that is missing or if there is a way by which the storage class can assign required permission automatically.

Thank you very much in advance.

Regards,
Nithin
