### ISSUE TITLE
[local-volume] Discover local PVs with configurable settings

### ISSUE THREAD

**Issue by ddysher** [kubernetes-incubator/external-storage#131]
Right now, discovery setting (e.g. host path for discovering PVs) is hard-coded in static provisioner, we should make it configurable for users via configmap.

**Comment by ddysher** [comment]
Draft idea for configurable local volume settings.

### User config struct

Change raw user config to the following.  This is a bit verbose since most of the time, user might just use one hostDir for their local volume, but I think it's no harm to make the struct more extensible; particularly when this is mostly a one-time configuration.

```go
// UserConfig stores all the user-defined parameters to the provisioner
type UserConfig struct {
    // Node object for this node
    Node *v1.Node
    // key = storageclass, value = mount configuration for the storageclass
    DiscoveryMap map[string][]MountConfig
}

// MountConfig stores a configuration for discoverying a specific storageclass
type MountConfig struct {
    // The hostpath directory
    HostDir string
    // The mount point of the hostpath volume
    MountDir string
    // The relative path for the mount point
    // RelativePaths is optional. If not specified, root of MountDir will
    // be used for discovery instead
    // +optional
    RelativePaths []string
}
```

For example:

```json
{
  "sc-fast": {
    "mountConfigs": [
      {
        "hostDir": "/mnt/local-fast-1",
        "mountDir": "/local-sata-ssd",
      },
      {
        "hostDir": "/mnt/local-fast-2",
        "mountDir": "/local-m2-ssd",
        "relativePaths": ["dir1", "dir2"],
      }
    ],
  },
  "sc-slow": {
    "mountConfigs": [
      {
        "hostDir": "/mnt/local-slow-3",
        "mountDir": "/local-disk",
      }
    ]
  }
}
```

### DaemonSet Creation

The above config must also be injected into daemonset yaml file for volume mount. For example, the above config yields the following yaml file:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
spec:
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      containers:
      - name: provisioner
        image: "gcr.io/msau-k8s-dev/local-volume-provisioner:latest"
        imagePullPolicy: Always
        volumeMounts:
        - name: discovery-vol-1
          mountPath: "/local-sata-ssd"
        - name: discovery-vol-2
          mountPath: "/local-m2-ssd"
        - name: discovery-vol-3
          mountPath: "/local-disk"
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: discovery-vol-1
        hostPath:
          path: "/mnt/local-fast-1"
      - name: discovery-vol-2
        hostPath:
          path: "/mnt/local-fast-2"
      - name: discovery-vol-3
        hostPath:
          path: "/mnt/local-slow-3"
      serviceAccount: local-storage-admin
```

### Summary

In short, there is one configuration source, and we need to propagate to daemonset pod, and yaml file. `provisioner-daemonset.yaml` will be converted to a template and final yaml file is generated based on user config. I think provisioner itself along can't do both work, there's a couple of options:

- Do not start daemonset from command line; rather, run a bootstrap pod which takes
  in the config, generates yaml file, then creates daemonset and configmap.
  - pros: hides all details, extensible, automation
  - cons: different ux
- Run a pre-processing shell script to generate the yaml and create configmap.
  - pros: easy to implement
  - cons: less extensible

I've also considered features like PodPreSet, but doesn't work well in our scenario (because now you need to create a PodPreSet and ConfigMap, so config is duplicated in two places). There can be others as well; personally, I prefer the first option.

 @msau42 @jsafrane @wongma7  @humblec
