### ISSUE TITLE
The inability to create a custom path and name for PV.

### ISSUE THREAD

**Issue by Bledai** [kubernetes-incubator/external-storage#1339]
As I can see the [pvName](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go#L65) and the [pvPath](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go#L74) to create a PV are strictly defined. However, for our purposes, a flexible solution is needed. 

To decouple PV settings of NFS client (mount options, path, etc) and PVC settings it is better to put all these settings into StorageClass and makes PV-provisioner work on it. 

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: managed-nfs-storage-test-2
provisioner: fuseim.pri/ifs 
parameters:
  archiveOnDelete: "false"
  pathPattern: "{pvc.namespace}/{pvc.name}"
  namePattern: "{pvc.name}-{pvc.annotations.volume.beta.kubernetes.io/storage-class}"
```
