### ISSUE TITLE
Does nfs provisioner support mount options or parameters?

### ISSUE THREAD

**Issue by cainzhong** [kubernetes-incubator/external-storage#1344]
Does nfs provisioner support mount options or parameters? Something like `anonuid`, `anongid`, `root_squash`.
or `(rw,sync,anonuid=1999,anongid=1999,root_squash`

I have tried 
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-dynamic
provisioner: example.com/nfs
parameters:
   anonuid: "2000"
   anongid: "2000"
mountOptions:
  - rw
  - root_squash
  - anonuid=10000
  - anongid=10000
```

But it doesn't work. It failed with below message.

`Failed to provision volume with StorageClass "nfs-dynamic": error validating options for volume: invalid parameter: "anongid"`
