### ISSUE TITLE
aws-efs :: Error - no mount entry found?

### ISSUE THREAD

**Issue by rasheedamir** [kubernetes-incubator/external-storage#260]
`efs-provisioner` fails to start with this error:

```
F0726 09:54:07.732751       1 efs-provisioner.go:71] no mount entry found for fs-c1518208.efs.eu-west-1.amazonaws.com
```

I followed all steps in the `README.md` but not sure what is missing though?

I have two nodes; and I manually mounted the EFS on both nodes and I can see files.

@wongma7 can you please guide?

**Comment by wongma7** [comment]
Please post your deployment yaml, it must have something like this

      volumes:
        - name: pv-volume
          nfs:
            server: fs-c1518208.efs.eu-west-1.amazonaws.com
            path: /persistentvolumes

**Comment by regnignuj** [comment]
Hi

I'm getting the same error.

I used a modified version of https://raw.githubusercontent.com/kubernetes-incubator/external-storage/master/aws/efs/deploy/manifest.yaml

Here's the deployment part.

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-88888888.efs.aa-aaaa-8.amazonaws.com
            path: /persistentvolumes

**Comment by wongma7** [comment]
Does it work if you run the container privileged?

**Comment by regnignuj** [comment]
I tried it (modified the yaml to this), but I still got the same error

```YAML
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          securityContext:
            privileged: true
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-88888888.efs.aa-aaaa-8.amazonaws.com
            path: /persistentvolumes
```
