### ISSUE TITLE
aws-efs efs volume claim "stuck in externalProvisioning"

### ISSUE THREAD

**Issue by snoby** [kubernetes-incubator/external-storage#323]
Hi,
I have a cluster v1.5.4 installed with kops on aws. I'm trying to use the EFS external storage allocator, however I'm running into an issue.  After following the install procedures the efs pvc is stuck and the error message from a describe on the pvc is ` cannot find provisioner "example.com/aws-efs", expecting that a volume for the claim is provisioned either manually or via external software`

```
snoby@mbp:~/work/Official/kube-vault-consul/efs-provisioner$ kubectl get storageclasses
NAME            TYPE
aws-efs         example.com/aws-efs
```
so it's installed and "there", the pod logs 
```
matt@mbp:~/work/Official/kube-vault-consul/efs-provisioner$ kubectl -n prod logs efs-provisioner-4261482999-ztdg4
I0829 20:06:02.409767       1 controller.go:407] Starting provisioner controller 7b72cb82-8cf5-11e7-9026-26e456c131ed!
```

And attached is my manifest.yaml file

Obviously, I've allocated the EFS file system in aws and put the correct security groups in place.  I'm stuck because everything seems to be correct:
```
matt@mbp:~/work/Official/kube-vault-consul/efs-provisioner$ kubectl describe storageclasses/aws-efs
Name:		aws-efs
IsDefaultClass:	No
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"kind":"StorageClass","apiVersion":"storage.k8s.io/v1beta1","metadata":{"name":"aws-efs","creationTimestamp":null},"provisioner":"example.com/aws-efs"}
Provisioner:	example.com/aws-efs
Parameters:	<none>
No events.
```

Thanks for any guidance.

**Comment by wongma7** [comment]
hi, could you please try attaching your manifest.yaml again, I don't see it. The StorageClass looks fine.

that `externalProvisioning` event on the PVC is normal, getting stuck there is not

**Comment by snoby** [comment]
I will place the manifest here:
```YAML
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
  namespace: prod
data:
  file.system.id: fs-ff523eb6
  aws.region: us-east-1
  provisioner.name: example/aws-efs
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws-secret-access-key
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-ff523eb6.efs.us-east-1.amazonaws.com
            path: /
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: aws-efs
provisioner: example.com/aws-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  namespace: prod
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---


```
