### ISSUE TITLE
aws-efs "Error getting server version: the server has asked for the client to provide credentials"

### ISSUE THREAD

**Issue by skornehl** [kubernetes-incubator/external-storage#340]
Hey,

I'm trying to get the EFS provider running. My config ist this:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
data:
  file.system.id: fs-xxxxxxxx
  aws.region: eu-west-1
  provisioner.name: example.com/aws-efs
---
kind: Secret
apiVersion: v1
metadata:
  name: aws-credentials
type: Opaque
data:
  aws-access-key-id: -Key-
  aws-secret-access-key: -Secret-
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws-secret-access-key
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-xxxxxxxx.efs.eu-west-1.amazonaws.com
            path: /
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: aws-efs
provisioner: example.com/aws-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
```

I'm pretty sure the credentials are right (using them with the CLI) but the container says otherwise:

kubectl logs efs-provisioner-753300497-r25xn
F0904 07:16:00.503006       1 efs-provisioner.go:281] Error getting server version: the server has asked for the client to provide credentials

Any way to get more debug info here?

Thanks for any help!
