### ISSUE TITLE
[local-volume] refactor format of local-volume-config

### ISSUE THREAD

**Issue by sbezverk** [kubernetes-incubator/external-storage#343]
Currently configuration for local volumes for the provisioner is stored in the configmap in json format.  @ianchakeres has suggested to switch to a more user friendly format.
Including @msau42  for the discussion.

**Comment by msau42** [comment]
@ianchakeres suggested to make the storage class mapping its own field so that you can add other global parameters.  I suggested to make it more user friendly by not using encoded json.  So I think the format could look something like this:

```
kind: ConfigMap
metadata:
  name: local-volume-config
  namespace: kube-system
data:
  someOtherParam: |
    foo value
  storageClassMap: |
    local-fast: 
       hostDir: "/mnt/ssds",
       mountDir: "/local-ssds"
    local-slow:
       hostDir: "/mnt/hdds",
       mountDir: "/local-hdds"
    local-storage:
      hostDir: "/mnt/disks"
```

What do you guys think?

**Comment by sbezverk** [comment]
@msau42 It looks more user friendly for sure but we need to evaluate how this structure will be represented in a mounted mode. Also before we were relaying on json decoding for syntax validation, with this approach we need to validate syntax of provided information in the code..

**Comment by msau42** [comment]
I believe each high level key is a file, and the value is the contents.

Yeah if the syntax validation and conversion is too complicated, then we can stick to encoded json.

**Comment by sbezverk** [comment]
how about yaml? I think it is easier for eyes of user and there are library to parse it?

**Comment by msau42** [comment]
Yeah I guess it shouldn't be too bad to go from yaml -> json -> struct?

**Comment by sbezverk** [comment]
We could do yaml to struct without intermediate json conversion.

**Comment by ianchakeres** [comment]
Three comments:

1) I am fine with yaml or json.

2) How about making it look a little more like other kubernetes manifests for the list of directories that will be managed by the local provisioner. Here's what I'm thinking...

```
kind: ConfigMap
metadata:
  name: local-volume-config
  namespace: kube-system
data:
   top-level-key: value
   local-volumes:
      - name: local-ssd
         storageClassName: gold
         hostDir: "/mnt/ssds",
         mountDir: "/local-ssds"
      - name: local-hdd:
         storageClassName: slow
         hostDir: "/mnt/hdds",
         mountDir: "/local-hdds"
```



3) I'd also be fine with dropping everything into a single top level `config.file` so that we don't have to dive down into each directory for each of the different key/value pairs. Below I've translated an example from the configmap documentation [link](https://kubernetes.io/docs/tasks/configure-pod-container/configmap/)
```
data:
    config.file: |-
    property.1=value-1
    property.2=value-2
   #aka everything with data in my example higher in this comment

**Comment by sbezverk** [comment]
@ianchakeres I tried to create a configmap based on option 2 and it is failing, it does not like 
"-name". 
error: error converting YAML to JSON: yaml: line 9: mapping values are not allowed in this context
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-volume-config
  namespace: kube-system
data:
   top-level-key: value
   local-volumes:
      - name: local-ssd
         storageClassName: gold
         hostDir: "/mnt/ssds"
         mountDir: "/local-ssds"
      - name: local-hdd:
         storageClassName: slow
         hostDir: "/mnt/hdds"
         mountDir: "/local-hdds"
```
