### ISSUE TITLE
LocalVolume not support Multiple VolumeClaims

### ISSUE THREAD

**Issue by xiaoshengaimm** [kubernetes-incubator/external-storage#380]
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: huangjs-test
  labels:
    appId: huangjs-app
spec:
  serviceName: huangjs-test
  podManagementPolicy: Parallel
  updateStrategy:
    type: OnDelete
  replicas: 6
  template:
    metadata:
      name: huangjs-test-2
      labels:
        appId: huangjs-app
    spec:
      containers:
      - name: app1
        image:  nginx:last
        command: ["sleep", "902"]
        volumeMounts:
        - name: db
          mountPath: /data
        - name: logs
          mountPath: /logs
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 51475068Ki
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 51475068Ki
~                                 
```
when there is more than one VolumeClaimTemplates and mount to the pod，k8s scheduler boud the claims to the pv on different nodes. so failed to startup.

hope support multiple pvcs.
