### ISSUE TITLE
[aws-efs] Deleting the volume does not delete the actual folder on EFS

### ISSUE THREAD

**Issue by nqbao** [kubernetes-incubator/external-storage#416]
I notice that the folder on the EFS is not deleted after the PV is deleted, even if the reclaim policy is `Delete`. Is it a bug or a feature?

*Step to reproduce*:

Create a pvc and bound to a pod:

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: efs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs
```

After applying the manifest, we will see the volume and the folder on efs

```
➜  ~ kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                                   REASON    AGE
cluster-manager                            200Mi      RWX           Retain          Bound     infrastructure/cluster-manager                    5d
cluster-manager-legacy                     200Mi      RWX           Retain          Bound     infrastructure/cluster-manager-legacy             5d
pvc-c0fdf9ae-b437-11e7-97a4-12a022115dac   1Mi        RWO           Delete          Bound     default/efs
```

```
/mnt/efs# ll | grep efs
drwxrws--x  2 root 2000 6144 Oct 13 06:51 efs-pvc-239d9487-afe2-11e7-97a4-12a022115dac/
drwxrws--x  2 root 2000 6144 Oct 18 18:14 efs-pvc-32922e89-b430-11e7-97a4-12a022115dac/
drwxrws--x  2 root 2000 6144 Oct 18 19:08 efs-pvc-c0fdf9ae-b437-11e7-97a4-12a022115dac/
drwxrws--x  2 root 2004 6144 Oct 18 17:57 efs-pvc-dbad5f7b-b42d-11e7-97a4-12a022115dac
```

Now if i delete the claim and the pv

```
➜  ~ kubectl delete pvc efs
persistentvolumeclaim "efs" deleted

➜  ~ kubectl delete pv pvc-c0fdf9ae-b437-11e7-97a4-12a022115dac
persistentvolume "pvc-c0fdf9ae-b437-11e7-97a4-12a022115dac" deleted
```

The folder is still there on the efs folder

```
/mnt/efs# ll | grep efs
drwxrws--x  2 root 2000 6144 Oct 13 06:51 efs-pvc-239d9487-afe2-11e7-97a4-12a022115dac/
drwxrws--x  2 root 2000 6144 Oct 18 18:14 efs-pvc-32922e89-b430-11e7-97a4-12a022115dac/
drwxrws--x  2 root 2000 6144 Oct 18 19:08 efs-pvc-c0fdf9ae-b437-11e7-97a4-12a022115dac/
drwxrws--x  2 root 2004 6144 Oct 18 17:57 efs-pvc-dbad5f7b-b42d-11e7-97a4-12a022115dac/
```
