### ISSUE TITLE
NFS provisioning "timeout expired waiting for volumes to attach/mount for pod"

### ISSUE THREAD

**Issue by SacDin** [kubernetes-incubator/external-storage#555]
- The NFS provisioner has been successfully deployed
- PVC and PV are created for requested volume
- But, pod is unable to mount volume throwing following error : 
```
Unable to mount volumes for pod "myservice-db-6b5d6f8cb7-t7tp9_dsp(e5cb22d7-f7cf-11e7-ba7d-b4b52f633558)": timeout expired waiting for volumes to attach/mount for pod "sd"/"myservice-db-6b5d6f8cb7-t7tp9". list of unattached/unmounted volumes=[sd-myservice-db]
```

**Comment by edify42** [comment]
Kube version?

**Comment by maha-v** [comment]
I am also running into the same issue. Any found a root cause ?

**Comment by agustinvinao** [comment]
Kubernetes 1.9.5

**Comment by dshkliaiev** [comment]
Any update?

**Comment by natcho** [comment]
I have also seen this problem sporadically in k8s 1.8.2. What I have found so far is that the directory that should back the provisioned volume was not created, therefore it cannot be mounted.

**Comment by wydwww** [comment]
I tried nfs client provisioner and everything worked fine.

**Comment by natcho** [comment]
As I wrote, this happens sporadically, it works as expected most of the time.

**Comment by sv01a** [comment]
Try to restart nfs provisioner pod. Works for me

**Comment by wongma7** [comment]
sorry these issues are hard to debug. If this occurs again please open a new issue or contact me on slack @mawong and try to preserve logs of the kubelet the pod is running on, it may have more information about why the mount call failed.

The directory not being created is especially weird as the provisioner should always do that long before it creates a PV

Generally I recommend setting up a simple nfs server and using nfs-client provisioner if nfs-provisioner doesn't immediately work.

/area nfs

**Comment by g0blin79** [comment]
I reopen this issue, because I had this error very often.

With a NFS server provisioner started, if I provision a new pvc all goes well.
If, for some reason, I remove the pod resource that is using this nfs pvc, then I re-deploy the same application, also specifying to use the existing pvc I had this error.

```
Unable to mount volumes for pod "redis-master-0_redis(a154b6c7-0a29-11ea-bd63-42010a9c012d)": timeout expired waiting for volumes to attach or mount for pod "redis"/"redis-master-0". list of unmounted volumes=[redis-data]. list of unattached volumes=[health config redis-data redis-tmp-conf redis-sa-token-wvvfv]
```
This is only an example. I had this error for different applications, not only for redis.

Some specification:
- I'm using nfs-server-provider on GKE
- I set reclaim policy as "Retain" for provisioned pvc
- I'm using helm charts: both for NFS provisioner and for client pods.
- the directory is correctly created on NFS provisioner (I checked)
- I'm using the same NFS server provisioner to provision more than a PVC for more than an application in different nodepools and namespaces.

This is the "values.yaml" I used to deploy nfs-server-provisioner:
```
# Default values for nfs-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# imagePullSecrets:

image:
  repository: quay.io/kubernetes_incubator/nfs-provisioner
  tag: v2.2.1-k8s1.12
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

  nfsPort: 2049
  mountdPort: 20048
  rpcbindPort: 51413
  # nfsNodePort:
  # mountdNodePort:
  # rpcbindNodePort:

  externalIPs: []

persistence:
  enabled: true

  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  accessMode: ReadWriteOnce
  size: 50Gi

## For creating the StorageClass automatically:
storageClass:
  create: true

  ## Set a provisioner name. If unset, a name will be generated.
  # provisionerName:

  ## Set StorageClass as the default StorageClass
  ## Ignored if storageClass.create is false
  defaultClass: false

  ## Set a StorageClass name
  ## Ignored if storageClass.create is false
  name: nfs-datafiles

  # set to null to prevent expansion
  allowVolumeExpansion: true
  ## StorageClass parameters
  parameters: {}

  mountOptions:
    - vers=4.1
    - noatime

  ## ReclaimPolicy field of the class, which can be either Delete or Retain
  reclaimPolicy: Retain

## For RBAC support:
rbac:
  create: true

  ## Ignored if rbac.create is true
  ##
  serviceAccountName: default

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
            - storage-nodepool
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: cloud.google.com/gke-nodepool
          operator: In
          values:
            - storage-nodepool
```
