### ISSUE TITLE
Digital Ocean external volume test failing (again)

### ISSUE THREAD

**Issue by lloeki** [kubernetes-incubator/external-storage#571]
This is kind of a followup to #529 and may provide additional info to add to #531.

Basically I am faced with a variation of the issue encountered by @tianhuil and proceeded to diagnose it further using the fantastic @klausenbusk feedback provided in that issue.

Situation: a fairly standard `kubeadm` cluster on Digital Ocean using kube v1.9.2 on CoreOS Container Linux, together with flannel 0.9.1 (that rules out some DNS issues). I followed the current README instructions and was faced with the exact same problem. The variation is that since CoreOS mounts `/usr` read-only, adjustments have to be made.

### Part 1: exposing plugins outside of `/usr`

So, first things first, the kubernetes side of things:

`mkdir -p /etc/kubernetes/kubelet-plugins/volume`
and add `--volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume` to `kubelet` arguments via `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` is easy enough.

(followed by `systemctl daemon-reload`)

And as seen in the other issue, I updated `/etc/kubernetes/manifests/kube-controller-manager.yaml` as follows:

```
  volumes:
  - hostPath:
      path: /etc/kubernetes/kubelet-plugins/volume/
      type: DirectoryOrCreate
    name: flexvolume-mount
```

(followed by `systemctl restart kubelet`)

`kubectl describe pod -n kube-system -l component=kube-controller-manager` now shows the volume as in the other issue.

Now, using the following as is documented in the README:

```
# digitalocean-flexplugin-deploy.yaml 
      volumes:
      - hostPath:
          path: /etc/kubernetes/kubelet-plugins/volume
        name: flexvolume-mount
```

And it fails as `kubectl describe pvc` is stuck on `ExternalProvisioning`, waiting for a volume to be created.

A look at `kubectl logs -n kube-system -l component=kube-controller-manager` quickly shows that the controller manager *still* looks for plugins in `/usr/libexec/kubernetes/kubelet-plugins/volume/exec`:

```
probe.go:215] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
```

Oops, let's update `/etc/kubernetes/manifests/kube-controller-manager.yaml` with the proper flag and `systemctl restart kubelet` again:

```
spec:
  containers:
  - command:
    - kube-controller-manager
    - --flex-volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume
  volumes:
  - hostPath:
      path: /etc/kubernetes/kubelet-plugins/volume/
      type: DirectoryOrCreate
    name: flexvolume-mount
```

Let's check at `kubectl logs -n kube-system -l component=kube-controller-manager`:

```
probe.go:215] Flexvolume plugin directory at /etc/kubernetes/kubelet-plugins/volume does not exist. Recreating.
```

What?

```
$ kubectl exec -n kube-system -it kube-controller-manager-coreos-fra1-01 -- find /etc/kubernetes/kubelet-plugins/volume/
/etc/kubernetes/kubelet-plugins/volume/
```

Hmm. Turns out adding volumes is not sufficient, you also need to update volume mounts:

```
spec:
  containers:
  - command:
    - kube-controller-manager
    - --flex-volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume
  - volumeMounts:
    - mountPath: /etc/kubernetes/kubelet-plugins/volume
      name: flexvolume-mount
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/kubelet-plugins/volume/
      type: DirectoryOrCreate
    name: flexvolume-mount
```

`systemctl restart kubelet`, and:

```
$ kubectl exec -n kube-system -it kube-controller-manager-coreos-fra1-01 -- find /etc/kubernetes/kubelet-plugins/volume/
/etc/kubernetes/kubelet-plugins/volume/
/etc/kubernetes/kubelet-plugins/volume/external-storage~digitalocean
/etc/kubernetes/kubelet-plugins/volume/external-storage~digitalocean/do_token
/etc/kubernetes/kubelet-plugins/volume/external-storage~digitalocean/digitalocean
```

Now things are finally looking fine!

### Part 2: pvc is still stuck

```
$ kubectl get pvc
NAME      STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pv1       Pending                                       default        1h
$ kubectl describe pvc
Name:          pv1
Namespace:     default
StorageClass:  default
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner=external/digitalocean
Finalizers:    []
Capacity:      
Access Modes:  
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  ExternalProvisioning  3m (x242 over 1h)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "external/digitalocean" or manually created by system administrator
```

Meanwhile, `kubectl logs -n kube-system -l component=kube-controller-manager  | grep -i flex` is empty, and without `grep` the log is filled with:

```
I0124 12:47:34.617284       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"pv1", UID:"8b65696e-00fb-11e8-aac8-6a940cb86d5b", APIVersion:"v1", ResourceVersion:"131470", FieldPath:""}): type: 'Normal' reason: 'ExternalProvisioning' waiting for a volume to be created, either by external provisioner "external/digitalocean" or manually created by system administrator
```

Perhaps more interesting is the following:

```
$ kubectl logs -l app=digitalocean-provisioner -n kube-system
I0124 11:13:16.045031       1 main.go:51] Provisioner external/digitalocean specified
I0124 11:13:16.045188       1 main.go:65] Building kube configs for running in cluster...
I0124 11:13:16.341288       1 controller.go:407] Starting provisioner controller 9343aab4-00f7-11e8-938f-0a580af40308!
E0124 11:13:16.343606       1 reflector.go:205] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:379: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:default" cannot list storageclasses.storage.k8s.io at the cluster scope
E0124 11:13:17.343746       1 reflector.go:205] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:411: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:kube-system:default" cannot list persistentvolumeclaims at the cluster scope
E0124 11:13:17.343894       1 reflector.go:205] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:412: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:serviceaccount:kube-system:default" cannot list persistentvolumes at the cluster scope
```

The last three lines being repeated ad nauseam.
