### ISSUE TITLE
Error getting server version - NFS Provisioner

### ISSUE THREAD

**Issue by vijayboopathy** [kubernetes-incubator/external-storage#626]
Kubernetes Version: v1.9.3
NFS Version: v1.0.8

I keep on getting the following error
`kubectl logs -f nfs-provisioner-79d9ff47cb-9gltj`
```
I0227 05:56:34.081863       1 main.go:65] Provisioner example.com/nfs specified
I0227 05:56:34.082112       1 main.go:85] Starting NFS server!
I0227 05:56:34.243370       1 server.go:139] starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576
I0227 05:56:34.243460       1 server.go:150] ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576
F0227 05:57:04.254086       1 main.go:142] Error getting server version: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout
```

Deployment file of NFS Provisioner
```
kind: Service
apiVersion: v1
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-provisioner
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: nfs-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:v1.0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=example.com/nfs"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /tmp/nfs-provisioner
```

Control Plane components
`kubectl get pods -n kube-system`
```
calico-etcd-qtjwn                         1/1       Running   0          15h
calico-kube-controllers-d669cc78f-9q2vm   1/1       Running   0          15h
calico-node-h5smf                         2/2       Running   1          15h
calico-node-lxdwc                         2/2       Running   1          15h
calico-node-vh882                         2/2       Running   0          15h
etcd-kube-01                              1/1       Running   0          15h
kube-apiserver-kube-01                    1/1       Running   0          15h
kube-controller-manager-kube-01           1/1       Running   0          15h
kube-dns-6f4fd4bdf-cvkcz                  3/3       Running   0          15h
kube-proxy-ckslg                          1/1       Running   0          15h
kube-proxy-ncn79                          1/1       Running   0          15h
kube-proxy-p5nc8                          1/1       Running   0          15h
kube-scheduler-kube-01                    1/1       Running   0          15h
```
