### ISSUE TITLE
How to provision an already existing Block Storage PersistentVolume on DigitalOcean?

### ISSUE THREAD

**Issue by eddiewang** [kubernetes-incubator/external-storage#668]
Hi there,

I've been experimenting with the DigitalOcean provisioner, and it's been working pretty well for me (other than occasionally not deleting the Volume on reclaim).

I have an image with persistent data, that I would like to attach to a new k8 cluster. Is there a way to provision an existing PVC by passing the name of the volume?

Thanks for the help.

**Comment by klausenbusk** [comment]
> I've been experimenting with the DigitalOcean provisioner, and it's been working pretty well for me (other than occasionally not deleting the Volume on reclaim).

That sounds like a bug, does the log show anything? (`kubectl -n kube-system logs -l app=digitalocean-provisioner`)

> I have an image with persistent data, that I would like to attach to a new k8 cluster. Is there a way to provision an existing PVC by passing the name of the volume?

It is possible but a bit tricky. You would need to create the PVC and PV manually, ensure the PV name match the volume name and set the `digitalocean.external-storage.incubator.kubernetes.io/VolumeID` annotation correctly in the PV.

It is probably easier just creating a new PVC and just `rsync -a` the content from the existing volume.

**Comment by klausenbusk** [comment]
@eddiewang Did you solve the probme?/Can we close this issue?

**Comment by klausenbusk** [comment]
> In my case I have a couple of block data volumes, which contain data that will probably outlive a lot of clusters. I'm not sure but I guess it would be easier to create/maintain a PV config for those volumes. I could then just run kubectl create -f pv.yaml to attach the volumes to the new cluster. That would make data migration as simple, fast and scalable as it can get (at least in my imagination).

You could export the existing PVC/PV and create them in the new cluster. That should solve the "new cluster/migration" use case.

Something like:
```
kubectl get pvc <name> -o yaml > pvc
kubectl get pv <corresponding PVC) -o yaml > pv
kubectl create -f pvc
kubectl create -f pv
```

**Comment by klausenbusk** [comment]
> An example for this would be tremendously helpful! I'm currently looking at the auto generated PV/PVC configs in my cluster, but I can't really wrap my head around it.

Try this:
First create the PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Provisioner_Id: ""
    digitalocean.external-storage.incubator.kubernetes.io/VolumeID: <VolumeID>
    kubernetes.io/createdby: digitalocean-provisioner
    pv.kubernetes.io/provisioned-by: external/digitalocean
  labels:
    failure-domain.beta.kubernetes.io/zone: <region of the volume>
  name: <volumeName, should match exactly!>
  namespace: <namespace>
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: <size in Gi, ex: 1Gi)
  claimRef:
    name: <volumeName, should match exactly!>
    namespace: <namespace>
  flexVolume:
    driver: external-storage/digitalocean
  persistentVolumeReclaimPolicy: Delete
```

Then create the PVC (with the exact same name):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <volumeName, should match exactly!>
  namespace: <namespace>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: <size in Gi, ex: 1Gi)
  volumeName: <volumeName, should match exactly!>
```
