### ISSUE TITLE
[nfs-provisionner] Unable to share single files

### ISSUE THREAD

**Issue by oprietop** [kubernetes-incubator/external-storage#69]
Those are the volumeMouns of a Replication Controller mounted to the nfs-provisioner:
```
       volumeMounts:
          - name: nfs
            mountPath: /etc/nginx/nginx.conf
            subPath: robot/nginx/nginx.conf
          - name: nfs
            mountPath: /etc/nginx/fullchain.pem
            subPath: robot/nginx/fullchain.pem
          - name: nfs
            mountPath: /etc/nginx/privkey.pem
            subPath: robot/nginx/privkey.pem
          - name: nfs
            mountPath: /etc/nginx/.htpasswd
            subPath: robot/nginx/.htpasswd
          - name: nfs
            mountPath: /usr/share/nginx/html
            subPath: robot/www
```
The 3 first ones will never mount and fail (they are use to mount single files), only the fourt one  will work because is mounting a entire directory.

While i can recreate the pods to work with only directories is really handy to mount single files.
