### ISSUE TITLE
[efs-provisioner] Is it possible to customise "Persistent Volume" name

### ISSUE THREAD

**Issue by nagapavan** [kubernetes-incubator/external-storage#694]
I have configured an "efs-provisioner" on my cluster. I am wondering if there is a way to customize the name of "Persistent Volume" that gets created on applying the following config.
By default a random name like "pvc-8d4a5079-3272-11e8-9838-0ac28eb2d996" being generated.

I want to make this name pre-configured, so that I can avoid to get a list of Volumes for the Namespace and get the ID/name of the volume.

```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
```
