### ISSUE TITLE
[local-volume] running cockroach cluster in GKE local volumes fails

### ISSUE THREAD

**Issue by lwsanty** [kubernetes-incubator/external-storage#726]
**aim** I want to run a cockroach cluster in GKE using nodes local volumes as datadirs
**steps**
1) create cluster in GKE
- api version `1.9.6-gke.0`
- nodes number: 3
- local SSDs per node: 1
2) create cluster role binding for rbac
```
kubectl create clusterrolebinding myname-cluster-admin-binding --clusterrole=cluster-admin --user=myname@example.org
```
3) create provisioner (from readme)
```
kubectl create -f provisioner/deployment/kubernetes/gce/class-local-ssds.yaml
kubectl create -f provisioner/deployment/kubernetes/gce/provisioner_generated_gce_ssd_volumes.yaml
```
4) run cockroach statefulset
```
kubectl create -f cockroachdb-statefulset.yaml
```
you can watch config here https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/cockroachdb-statefulset.yaml

and it's tweaked a bit, in the next section by adding storage class name `local-nvme` which was created in 3 
```
      volumes:
      - name: datadir
        persistentVolumeClaim: 
          claimName: datadir
  updateStrategy:
    type: RollingUpdate  
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:  
        - "ReadWriteOnce"
      storageClassName: "local-nvme"
      resources:
        requests:
          storage: 1Gi
```
**result**
cluster node is always in pending state
**note** running statefulset without local volumes works fine

Please navigate me what am I doing wrong :)
