### ISSUE TITLE
StorageClass does not support fstype parameter in snapshot-promoter Provisioner

### ISSUE THREAD

**Issue by joshisumit** [kubernetes-incubator/external-storage#879]
Kubernetes v1.9.5

```
$ cat <<EOF | kubectl apply -f -
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: snapshot-promoter
provisioner: volumesnapshot.external-storage.k8s.io/snapshot-promoter
parameters:
  type: gp2
  fsType: xfs
EOF
```

If I add fsType: xfs parameter, I will not be able to run PVC properly.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-snapshot
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: snapshot-promoter

```

PVC creation fails with an error:
`Warning  ProvisioningFailed    9s (x4 over 51s)  volumesnapshot.external-storage.k8s.io/snapshot-promoter Failed to provision volume with StorageClass "snapshot-promoter": invalid option "fsType" for volumesnapshot.external-storage.k8s.io/snapshot-promoter`

Default is `ext4` filesystem and it is hardcoded [here](https://github.com/kubernetes-incubator/external-storage/blob/master/snapshot/pkg/volume/awsebs/processor.go#L187)
