### ISSUE TITLE
[nfs-provisioner] Update storageClassName definition

### ISSUE THREAD

**Issue by michaeleino** [kubernetes-incubator/external-storage#898]
switch the storageClassName definition to adapt kubernetes changes..
 
[As Docs here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class):--
> In the past, the annotation volume.beta.kubernetes.io/storage-class was used instead of the storageClassName attribute. This annotation is still working, however it will become fully deprecated in a future Kubernetes release.

the yaml files is working... but the resulting volumes doesn't have the StorageClass field.
![screenshot from 2018-08-01 09-56-46](https://user-images.githubusercontent.com/6287237/43509046-dd9dab6a-9571-11e8-8c76-bb3adcfdf804.png)

Should be 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
```
