### ISSUE TITLE
local provisioner zero size

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-incubator/external-storage#968]
I'm trying to deploy the local provisioner via helm chart. I'm almost there, but have run into an issue where:
```
I0904 17:56:25.469173       1 discovery.go:298] Found new volume of volumeMode "Filesystem" at host path "/mnt/disks/1" with capacity 0, creating Local PV "local-pv-cfe51de1"
E0904 17:56:25.470188       1 discovery.go:323] Error creating PV "local-pv-cfe51de1" for volume at "/mnt/disks/1": PersistentVolume "local-pv-cfe51de1" is invalid: spec.capacity[storage]: Invalid value: "0": must be greater than zero
```

It fails to create the pv's.

I made the volumes like:
```
for x in `seq 1 10`; do
  mkdir -p /kube/backing/$x
  mkdir -p /mnt/disks/$x
  echo /kube/backing/$x /mnt/disks/$x none defaults,bind 0 0 >> /etc/fstab
  mount /mnt/disks/$x
done
```
And deployed with these values:
```yaml
common:
  namespace: local-volume

classes:
- name: local-storage
  hostDir: /mnt/disks
  blockCleanerCommand:
  # Do a quick reset of the block device during its cleanup.
  # - "/scripts/quick_reset.sh"
  # or use dd to zero out block dev in two iterations by uncommenting these lines.
  # - "/scripts/dd_zero.sh"
  # - "2"
  # or run shred utility for 2 iterations.
  - "/scripts/fsclean.sh"
  # or blkdiscard utility by uncommenting the line below.
  # - "/scripts/blkdiscard.sh"
  storageClass: true

daemonset:
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
```
