### ISSUE TITLE
NFS client  Provisioner ignores storage

### ISSUE THREAD

**Issue by aclowkey** [kubernetes-incubator/external-storage#989]
The client provisioner seems to ignore PVC's storage.

I have set up an NFS server with 10Gi files, and requests 50,000Gi, and successfully got them. 

`helm install --name nfs-client-provisioner --set nfs.server=0.0.0.0 --set nfs.path=/ stable/nfs-client-provisioner `

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overkill
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50000Gi
```

```
pvc-f32bfdba-ba82-11e8-a504-42010aa80fe4   50000Gi    RWO            Delete           Bound     default/overkill   nfs-client               38m
```
