### ISSUE TITLE
Ceph RBD resize volume

### ISSUE THREAD

**Issue by unteem** [kubernetes-incubator/external-storage#992]
Hi
I'm trying to resize a volume provisioned with ceph rbd provisioner.

Here is the error I get:
`Error expanding volume "indie-host/minio-indie-host" of plugin kubernetes.io/rbd : rbd info failed, error: executable file not found in $PATH`

Is it possible to resize a volume when using ceph rbd provisioner ?
kubernetes version: 1.10.3

**Comment by wongma7** [comment]
yes, once the volume is created by the provisioner it is like any rbd volume. That error sounds like the rbd executable is not on the node
/area ceph/rbd

**Comment by JrCs** [comment]
I have this error:
`Warning  VolumeResizeFailed     13s (x4 over 2m)  volume_expand                                                                       Error expanding volume "kube-system/claim1" of plugin kubernetes.io/rbd : failed to get admin secret from ["kube-system"/"ceph-admin-secret"]: failed to get secret from ["kube-system"/"ceph-admin-secret"]
`
The kube-system/ceph-admin-secret secret exist and it is used to create the volume.

What rules to ClusterRole I need to change to allow the expansion of volume ?

This is the current ClusterRole i use:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-provisioner
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

```
